name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NSIS Get
        run:
          shell:
              powershell: Invoke-WebRequest http://prdownloads.sourceforge.net/nsis/nsis-3.04-setup.exe?download -UseBasicParsing -OutFile nsis-3.04-setup.exe
    - name: NSIS Install
      run:
        shell:
              cmd: nsis-3.04-setup.exe /SD
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
